using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace teamseven.EzExam.Repository.Models
{
    [Table("exams")]
    public class Exam
    {
        [Key]
        [Column("Id")]
        public int Id { get; set; }

        [Required]
        [MaxLength(200)]
        [Column("Name")]
        public string Name { get; set; } = string.Empty;

        [MaxLength(1000)]
        [Column("Description")]
        public string? Description { get; set; }

        [Required]
        [Column("SubjectId")]
        public int SubjectId { get; set; }

        [Column("GradeId")]
        public int? GradeId { get; set; }

        [Column("LessonId")]
        public int? LessonId { get; set; }

        [Required]
        [Column("ExamTypeId")]
        public int ExamTypeId { get; set; }

        [Required]
        [Column("CreatedByUserId")]
        public int CreatedByUserId { get; set; }

        [Column("TimeLimit")]
        public int? TimeLimit { get; set; } // minutes - optional time limit

        [Column("TotalQuestions")]
        public int TotalQuestions { get; set; } = 0;

        [Column("TotalMarks")]
        public int? TotalMarks { get; set; } // optional total marks

        [Column("Duration")]
        public int Duration { get; set; } // minutes - actual test duration set by user

        [Column("TestConfiguration")]
        [MaxLength(2000)]
        public string? TestConfiguration { get; set; } // JSON configuration for test settings

        [Column("DifficultyDistribution")]
        [MaxLength(500)]
        public string? DifficultyDistribution { get; set; } // JSON: {"EASY": 5, "MEDIUM": 10, "HARD": 5}

        [Column("TopicDistribution")]
        [MaxLength(1000)]
        public string? TopicDistribution { get; set; } // JSON: {"Mechanics": 8, "Thermodynamics": 7}

        [Column("IsAutoGenerated")]
        public bool IsAutoGenerated { get; set; } = false; // true for AI-generated tests

        [Column("GenerationSource")]
        [MaxLength(50)]
        public string? GenerationSource { get; set; } // AI, USER_CART, STAFF

        [Column("AITestRecommendationId")]
        public int? AITestRecommendationId { get; set; } // Link to AI recommendation if applicable

        [Column("IsDeleted")]
        public bool IsDeleted { get; set; } = false;

        [Column("IsActive")]
        public bool IsActive { get; set; } = true;

        [Column("IsPublic")]
        public bool IsPublic { get; set; } = false;

        [Column("CreatedAt")]
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        [Column("UpdatedAt")]
        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

        // Navigation properties
        [ForeignKey("CreatedByUserId")]
        public virtual User CreatedByUser { get; set; } = null!;

        [ForeignKey("ExamTypeId")]
        public virtual ExamType ExamType { get; set; } = null!;

        [ForeignKey("SubjectId")]
        public virtual Subject Subject { get; set; } = null!;

        [ForeignKey("GradeId")]
        public virtual Grade? Grade { get; set; }

        [ForeignKey("LessonId")]
        public virtual Lesson? Lesson { get; set; }

        [ForeignKey("AITestRecommendationId")]
        public virtual AITestRecommendation? AITestRecommendation { get; set; }

        public virtual ICollection<ExamQuestion> ExamQuestions { get; set; } = new List<ExamQuestion>();
    }
}