using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace teamseven.EzExam.Services.Object.Responses
{
    public class ExamResponse
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public string? Description { get; set; }
        public int SubjectId { get; set; }
        public int? GradeId { get; set; }
        public int? LessonId { get; set; }
        public int ExamTypeId { get; set; }
        public int CreatedByUserId { get; set; }
        public int? TimeLimit { get; set; }
        public int TotalQuestions { get; set; }
        public int? TotalMarks { get; set; }
        public int Duration { get; set; }
        public string? TestConfiguration { get; set; }
        public string? DifficultyDistribution { get; set; }
        public string? TopicDistribution { get; set; }
        public bool IsAutoGenerated { get; set; }
        public string? GenerationSource { get; set; }
        public int? AITestRecommendationId { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public bool IsPublic { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }

        // Navigation properties for display
        public string? CreatedByUserName { get; set; }
        public string? ExamTypeName { get; set; }
        public string? LessonName { get; set; }
        public string? SubjectName { get; set; }
        public int QuestionCount { get; set; }
        public int HistoryCount { get; set; }
    }
}
